

SELECT * FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' 
AND DISTRICT='BEÞÝKTAÞ'
AND AGE=30


SELECT * FROM CUSTOMERS
WHERE GENDER='ERKEK'
AND CITY='ÝZMÝR'


SELECT * FROM CUSTOMERS
WHERE GENDER='ERKEK'
AND BIRTHDATE BETWEEN '1990-03-30' AND '1992-08-03'


SELECT * FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' 
OR DISTRICT='BEÞÝKTAÞ'
OR AGE=30


SELECT * FROM CUSTOMERS
WHERE GENDER='ERKEK'
AND CITY='ÝZMÝR'