/* DISTINCT KOMUTU : tekrar eden komutlarý tekileþtirmek için kullanýlir

SELECT DISTINCT 
KOLON1,KOLON2,KOLON3..
FROM TABLOADI
WHERE <ÞARTLAR>

*/

SELECT DISTINCT CITY ,DISTRICT
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'


SELECT DISTINCT GENDER 
FROM CUSTOMERS
WHERE CITY='ANKARA'


SELECT DISTINCT AGE 
FROM CUSTOMERS
WHERE CITY='ANKARA'
