/*
SELECT KOLON1,KOLON2..
FROM TABLOADI
WHERE <ÞARTLAR>
ORDER BY KOLON1 ASC,KOLON2 DESC
*/

SELECT *FROM CUSTOMERS
ORDER BY ID DESC


SELECT *FROM CUSTOMERS
ORDER BY CUSTOMERNAME DESC


SELECT *FROM CUSTOMERS
ORDER BY BIRTHDATE DESC


SELECT *FROM CUSTOMERS
ORDER BY CITY DESC,CUSTOMERNAME ASC


SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'
ORDER BY CITY ,DISTRICT,CUSTOMERNAME


SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'
ORDER BY 2