/*
SELECT KOLON1,KOLON2...
FROM TABLOADI
WHERE <ÞARTLAR>
*/

/*
=  Eþittir
<> Eþit deðildir
< küçüktür
> büyüktür
BETWEEN arasýndadýr
LIKE    ile baþlar ile biter içerir
IN      içindedir
NOT LÝKE  ile baþlamaz ,ile bitmez ,içermez
NOT IN   içinde deðildir
*/


SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME='FATMA ÞEN'


SELECT * FROM CUSTOMERS
WHERE CITY='ANKARA'


SELECT * FROM CUSTOMERS
WHERE CITY<>'ANKARA'


SELECT * FROM CUSTOMERS
WHERE NOT CITY='ANKARA'


SELECT * FROM CUSTOMERS
WHERE CITY<>'ÝZMÝR'


SELECT * FROM CUSTOMERS
WHERE GENDER='K'


SELECT * FROM CUSTOMERS
WHERE AGE>30


SELECT * FROM CUSTOMERS
WHERE  AGE BETWEEN 30 AND 35


SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'ALÝ%'


SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%AN'


SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%AN%'


SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME NOT LIKE 'ALÝ%'


SELECT *FROM CUSTOMERS
WHERE CITY IN('ÝZMÝR','ANKARA')


SELECT *FROM CUSTOMERS
WHERE CITY IN('ÝZMÝR','ANKARA') AND CUSTOMERNAME LIKE 'ALÝ%'


SELECT *FROM CUSTOMERS
WHERE CITY NOT IN('ÝSTANBUL','ÝZMÝR','ANKARA')


UPDATE CUSTOMERS
SET GENDER ='ERKEK' 
WHERE GENDER='E'


UPDATE CUSTOMERS
SET GENDER ='KADIN' 
WHERE GENDER='K'


DELETE FROM CUSTOMERS 
WHERE ID=18

