
/*
SELECT 
A.KOLON1,A.KOLON2,B.KOLON3,B.KOLON4
FROM TABLO1 A
JOIN TABLO2 B ON A.PK_KOLON=B.FK_KOLON
*/

SELECT U.NAMESURNAME,U.EMAIL,A.ADDRESSTEXT,C.COUNTRY,CT.CITY,D.DISTRICT,T.TOWN
FROM
USERS U
JOIN ADRESS A ON A.USERID=U.ID
JOIN COUNTRIESS C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN TOWNS T ON T.ID=A.TOWNID

SELECT*FROM ADRESS
SELECT*FROM USERS