--bir günün maðaza bazlý satýþ rakamlarýný getirme 


SELECT *FROM SALES
WHERE DATE2='2019-01-01'


SELECT DATE2,CITY,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
WHERE DATE2='2019-01-01' 
GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC