---ürün kategorilerine göre satýþ rakamlarýný getirme


SELECT CATEGORY1,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS RAWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT
FROM SALES
GROUP BY CATEGORY1
ORDER BY CATEGORY1



SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS RAWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT
FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
