
SELECT CONVERT(DATE,DATE_) AS DATE2,*
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_


--VERÝ DÖNÜÞTÜREME
SELECT CONVERT (DATE,'2019-01-01 08:07:24.000')
SELECT CONVERT (TIME,'2019-01-01 08:07:24.000')


UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)


SELECT CITY,DATE2,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2

SELECT*FROM SALES
