--maðazalarýn müþteri sayýsýný getirme

SELECT CUSTOMERNAME,
FICHENO,COUNT(*)
FROM SALES WHERE MONTHNAME_='01. OCAK'
AND CITY='ADANA'
GROUP BY CUSTOMERNAME, FICHENO


SELECT CITY,
COUNT (DISTINCT FICHENO) AS CUSTOMERCOUNT,
COUNT(DISTINCT CUSTOMERNAME) AS UNIQCUSTOMER,
COUNT(*) AS ITEMCOUNT
FROM SALES 
WHERE MONTHNAME_='01. OCAK'
GROUP BY CITY
ORDER BY CITY

